### ISSUE TITLE
Email validation module

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2542]
The basic requirement is that before a user is created, we know the email address is valid.  I think Sarah is envisioning the typical "go check your email for a link" kind of functionality.

**Comment by teodorescuserban** [comment]
+1 on clicking a link sent by email.

**Comment by mbellotti** [comment]
Look into newest CKAN, have this started this already?

**Comment by danmihaila** [comment]
@mbellotti bellow there are some failing nose tests. I think they are related to this testing.You can check below.
Also, please note dev is redeployed an ready to be tested

++++++++++++++++++++++++++++++++++++++++++++++++++++
Running tests for plugin ckanext-hdx_theme
......../srv/ckan/ckanext-hdx_users/ckanext/hdx_users/actions/create.py:2: DeprecationWarning: the md5 module is deprecated; use hashlib instead (edited)

Running tests for plugin ckanext-hdx_users

ERROR: test suite for <class 'ckanext.hdx_users.tests.test_emails.test_email_access.TestEmailAccess'>

Traceback (most recent call last):
 File "/usr/local/lib/python2.7/dist-packages/nose/suite.py", line 227, in run
   self.tearDown()
 File "/usr/local/lib/python2.7/dist-packages/nose/suite.py", line 350, in tearDown
   self.teardownContext(ancestor)
 File "/usr/local/lib/python2.7/dist-packages/nose/suite.py", line 366, in teardownContext
   try_run(context, names)
 File "/usr/local/lib/python2.7/dist-packages/nose/util.py", line 469, in try_run
   return func()
 File "/srv/ckan/ckanext-hdx_theme/ckanext/hdx_theme/tests/hdx_test_base.py", line 55, in teardown_class
   model.repo.rebuild_db()
 File "/srv/ckan/ckan/model/**init**.py", line 281, in rebuild_db
   self.delete_all()
 File "/srv/ckan/ckan/model/**init**.py", line 304, in delete_all
   connection.execute('delete from "%s"' % table.name)
 File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1449, in execute
   params)
 File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1628, in _execute_text
   statement, parameters
 File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1698, in _execute_context
   context)
 File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1691, in _execute_context
   context)
 File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 331, in do_execute
   cursor.execute(statement, parameters)
ProgrammingError: (ProgrammingError) relation "validation_tokens" does not exist
LINE 1: delete from "validation_tokens"
                   ^
'delete from "validation_tokens"' {}

---

Ran 2 tests in 10.886s

FAILED (errors=1)

**Comment by mbellotti** [comment]
Okay the first one is easy to fix, the second one means you didn't run the
initdb paster command

**Comment by cjhendrix** [comment]
Tested on stag and not working, but I think maybe we can't send emails from stag?   It allowed me to create an account immediately and begin working. Reopening just to ask the question about what to expect on stag.

**Comment by danmihaila** [comment]
@cjhendrix this was tested yesterday. We agreed that we will not deploy email validation yet, and we will wait for 2.3 migration and new registration module. I removed the module, so that's why you see the old behaviour. I will move this issue into backlog until we decide to re-integrate it.

**Comment by mbellotti** [comment]
I thought we had agreed to keep it enabled on staging?

**Comment by danmihaila** [comment]
yes, but we will use staging to test before going to prod. I assume we will have the email validation module on dev or on another stag2 server.
