### ISSUE TITLE
Nose tests errors

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2566]
After the latest changes with custom pages we have this errors

======================================================================                                                                [55/1980]
## ERROR: ckanext.hdx_org_group.tests.test_auth.TestOrgAuth.test_edit_org

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(_self.arg)
  File "/srv/ckan/ckanext-hdx_org_group/ckanext/hdx_org_group/tests/test_auth.py", line 42, in test_edit_org
    apikey=user.apikey, status=403)
  File "/srv/ckan/ckan/tests/**init**.py", line 462, in call_action_api
    extra_environ={'Authorization': str(apikey)}, status=status)
  File "/usr/local/lib/python2.7/dist-packages/webtest/app.py", line 838, in post
    content_type=content_type)
  File "/usr/local/lib/python2.7/dist-packages/webtest/app.py", line 810, in _gen_request
    expect_errors=expect_errors)
  File "/usr/local/lib/python2.7/dist-packages/webtest/app.py", line 1102, in do_request
    res = req.get_response(app, catch_exc_info=True)
  File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1049, in get_response
    application, catch_exc_info=True)
  File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/webtest/lint.py", line 179, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/srv/ckan/ckan/config/middleware.py", line 373, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/paste/cascade.py", line 130, in **call**
    return self.apps[-1](environ, start_response)
  File "/srv/ckan/ckan/config/middleware.py", line 238, in **call**
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/paste/registry.py", line 379, in **call**
    app_iter = self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/repoze/who/middleware.py", line 107, in **call**
    app_iter = app(environ, wrapper.wrap_start_response)
  File "/usr/local/lib/python2.7/dist-packages/pylons/middleware.py", line 201, in **call**
    self.app, environ, catch_exc_info=True)
  File "/usr/local/lib/python2.7/dist-packages/pylons/util.py", line 94, in call_wsgi_application
    app_iter = application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/weberror/errormiddleware.py", line 156, in **call**
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 147, in **call**
    resp = self.call_func(req, *args, *_self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 208, in call_func
    return self.func(req, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fanstatic/publisher.py", line 234, in **call**
    return request.get_response(self.app)
  File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 147, in **call**
    resp = self.call_func(req, _args, *_self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 208, in call_func
    return self.func(req, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fanstatic/injector.py", line 54, in **call**
    response = request.get_response(self.app)
  File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/beaker/middleware.py", line 73, in **call**
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/beaker/middleware.py", line 155, in **call**
    return self.wrap_app(environ, session_start_response)
  File "/usr/local/lib/python2.7/dist-packages/routes/middleware.py", line 131, in **call**
    response = self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/pylons/wsgiapp.py", line 125, in **call**
    response = self.dispatch(controller, environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/pylons/wsgiapp.py", line 324, in dispatch
    return controller(environ, start_response)
  File "/srv/ckan/ckan/controllers/api.py", line 70, in **call**
    return base.BaseController.**call**(self, environ, start_response)
  File "/srv/ckan/ckan/lib/base.py", line 346, in **call**
    res = WSGIController.**call**(self, environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py", line 221, in **call**
    response = self._dispatch_call()
  File "/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py", line 172, in _dispatch_call
    response = self._inspect_call(func)
  File "/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py", line 107, in _inspect_call
    result = self._perform_call(func, args)
  File "/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py", line 60, in _perform_call
    return func(**args)
  File "/srv/ckan/ckan/controllers/api.py", line 189, in action
    result = function(context, request_data)
  File "/srv/ckan/ckan/logic/__init__.py", line 419, in wrapped
    result = _action(context, data_dict, **kw)
  File "/srv/ckan/ckanext-hdx_org_group/ckanext/hdx_org_group/helpers/organization_helper.py", line 143, in hdx_organization_update
    result = hdx_group_or_org_update(context, data_dict, is_org=True)
  File "/srv/ckan/ckanext-hdx_org_group/ckanext/hdx_org_group/helpers/organization_helper.py", line 183, in hdx_group_or_org_update
    data_dict['customization'] = json.loads(data_dict['customization'])
KeyError: 'customization'

---

Ran 17 tests in 28.947s

FAILED (errors=1)

======================================================================                                                                [55/1877]
## ERROR: ckanext.hdx_package.tests.test_pages.test_breadcrumbs.TestBreadcrumbs.test_breadcrumb_on_dataset_page

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(_self.arg)
  File "/srv/ckan/ckanext-hdx_package/ckanext/hdx_package/tests/test_pages/test_breadcrumbs.py", line 41, in test_breadcrumb_on_dataset_page
    result = self.app.get(url)
  File "/usr/local/lib/python2.7/dist-packages/webtest/app.py", line 759, in get
    expect_errors=expect_errors)
  File "/usr/local/lib/python2.7/dist-packages/webtest/app.py", line 1102, in do_request
    res = req.get_response(app, catch_exc_info=True)
  File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1049, in get_response
    application, catch_exc_info=True)
  File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/webtest/lint.py", line 179, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/srv/ckan/ckan/config/middleware.py", line 373, in **call**
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/paste/cascade.py", line 130, in **call**
    return self.apps[-1](environ, start_response)
  File "/srv/ckan/ckan/config/middleware.py", line 238, in **call**
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/paste/registry.py", line 379, in **call**
    app_iter = self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/repoze/who/middleware.py", line 107, in **call**
    app_iter = app(environ, wrapper.wrap_start_response)
  File "/usr/local/lib/python2.7/dist-packages/pylons/middleware.py", line 201, in **call**
    self.app, environ, catch_exc_info=True)
  File "/usr/local/lib/python2.7/dist-packages/pylons/util.py", line 94, in call_wsgi_application
    app_iter = application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/weberror/errormiddleware.py", line 156, in **call**
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 147, in **call**
    resp = self.call_func(req, *args, *_self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 208, in call_func
    return self.func(req, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fanstatic/publisher.py", line 234, in **call**
    return request.get_response(self.app)
  File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 147, in **call**
    resp = self.call_func(req, _args, *_self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 208, in call_func
    return self.func(req, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fanstatic/injector.py", line 54, in **call**
    response = request.get_response(self.app)
  File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/beaker/middleware.py", line 73, in **call**
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/beaker/middleware.py", line 155, in **call**
    return self.wrap_app(environ, session_start_response)
  File "/usr/local/lib/python2.7/dist-packages/routes/middleware.py", line 131, in **call**
    response = self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/pylons/wsgiapp.py", line 125, in **call**
    response = self.dispatch(controller, environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/pylons/wsgiapp.py", line 324, in dispatch
    return controller(environ, start_response)
  File "/srv/ckan/ckan/lib/base.py", line 346, in **call**
    res = WSGIController.**call**(self, environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py", line 221, in **call**
    response = self._dispatch_call()
  File "/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py", line 172, in _dispatch_call
    response = self._inspect_call(func)
  File "/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py", line 107, in _inspect_call
    result = self._perform_call(func, args)
  File "/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py", line 60, in _perform_call
    return func(**args)
  File "/srv/ckan/ckanext-hdx_package/ckanext/hdx_package/controllers/dataset_controller.py", line 680, in read
    org_id = c.pkg_dict.get('organization',{}).get('id', None)
AttributeError: 'NoneType' object has no attribute 'get'

---

Ran 11 tests in 46.167s

FAILED (errors=1)

**Comment by alexandru-m-g** [comment]
Committed fix for the 2nd nose test. 

The first one is related to #2569. When that will be fixed the nose test will probably work.

**Comment by alexandru-m-g** [comment]
All tests run now ok on dev so I'm closing this ticket.
