### ISSUE TITLE
Nosetest failing on 

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#3434]
# 
## FAIL: ckanext.hdx_search.tests.test_search_results.test_search_results.TestHDXSearchResults.test_hdx_search_results

Traceback (most recent call last):
 File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
   self.test(*self.arg)
 File "/srv/ckan/ckanext-hdx_search/ckanext/hdx_search/tests/test_search_results/test_search_results.py", line 57, in test_hdx_search_results
   assert dataset_counts == 3, '3 datasets'
AssertionError: 3 datasets

**Comment by alexandru-m-g** [comment]
I reverted part of this comit: https://github.com/OCHA-DAP/hdx-ckan/commit/279c4bb2e5f689c2e549fe06236bfdc9a880e4c6

Not sure why the dataset_count was expected to be 3. I think it should be 1 as there's only one test dataset that matches the query AFAIK.
