### ISSUE TITLE
Nosetest errors - featured orgs

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3501]
@mbellotti there are several errors related to 3 nosetests you added. You could fix the first error by importing user_extra plugin into test and changes to create_test_data I think. Check how is done in other tests. The other errors are related to missing imports
## ERROR: ckanext.hdx_org_group.tests.test_controller.test_custom_org_controller.TestMembersController.test_edit_custom_orgs

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(_self.arg)
  File "/srv/ckan/ckanext-hdx_org_group/ckanext/hdx_org_group/tests/test_controller/test_custom_org_controller.py", line 148, in test_edit_custom_orgs
    result = self.app.get(url, extra_environ={'Authorization': str(testsysadmin.apikey)})
  File "/usr/local/lib/python2.7/dist-packages/webtest/app.py", line 759, in get
    expect_errors=expect_errors)
  File "/usr/local/lib/python2.7/dist-packages/webtest/app.py", line 1102, in do_request
    res = req.get_response(app, catch_exc_info=True)
  File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1049, in get_response
    application, catch_exc_info=True)
  File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/webtest/lint.py", line 179, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/srv/ckan/ckan/config/middleware.py", line 368, in **call**
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/paste/cascade.py", line 130, in **call**
    return self.apps[-1](environ, start_response)
  File "/srv/ckan/ckan/config/middleware.py", line 232, in **call**
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/paste/registry.py", line 379, in **call**
    app_iter = self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/repoze/who/middleware.py", line 87, in **call**
    app_iter = app(environ, wrapper.wrap_start_response)
  File "/usr/local/lib/python2.7/dist-packages/pylons/middleware.py", line 201, in **call**
    self.app, environ, catch_exc_info=True)
  File "/usr/local/lib/python2.7/dist-packages/pylons/util.py", line 94, in call_wsgi_application
    app_iter = application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/weberror/errormiddleware.py", line 156, in **call**
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 147, in **call**
    resp = self.call_func(req, *args, *_self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 208, in call_func
    return self.func(req, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fanstatic/publisher.py", line 234, in **call**
    return request.get_response(self.app)
  File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 147, in **call**
    resp = self.call_func(req, _args, *_self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 208, in call_func
    return self.func(req, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fanstatic/injector.py", line 54, in **call**
    response = request.get_response(self.app)
  File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/beaker/middleware.py", line 73, in **call**
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/beaker/middleware.py", line 155, in **call**
    return self.wrap_app(environ, session_start_response)
  File "/usr/local/lib/python2.7/dist-packages/routes/middleware.py", line 131, in **call**
    response = self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/pylons/wsgiapp.py", line 125, in **call**
    response = self.dispatch(controller, environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/pylons/wsgiapp.py", line 324, in dispatch
    return controller(environ, start_response)
  File "/srv/ckan/ckan/lib/base.py", line 338, in **call**
    res = WSGIController.**call**(self, environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py", line 221, in **call**
    response = self._dispatch_call()
  File "/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py", line 172, in _dispatch_call
    response = self._inspect_call(func)
  File "/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py", line 107, in _inspect_call
    result = self._perform_call(func, args)
  File "/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py", line 60, in _perform_call
    return func(**args)
  File "/srv/ckan/ckanext-hdx_org_group/ckanext/hdx_org_group/controllers/organization_controller.py", line 194, in edit
    return render(self._edit_template(c.group.type))
  File "/srv/ckan/ckan/lib/base.py", line 217, in render
    loader_class=loader_class)
  File "/usr/local/lib/python2.7/dist-packages/pylons/templating.py", line 249, in cached_template
    return render_func()
  File "/srv/ckan/ckan/lib/base.py", line 155, in render_template
    return render_jinja2(template_name, globs)
  File "/srv/ckan/ckan/lib/base.py", line 104, in render_jinja2
    return template.render(**extra_vars)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/ckan/ckanext-hdx_theme/ckanext/hdx_theme/templates/organization/edit.html", line 1, in top-level template code
    {% extends "organization/base_form_page.html" %}
  File "/srv/ckan/ckan/templates/organization/base_form_page.html", line 1, in top-level template code
    {% extends "organization/edit_base.html" %}
  File "/srv/ckan/ckanext-hdx_theme/ckanext/hdx_theme/templates/organization/edit_base.html", line 3, in top-level template code
    {% set organization = c.group_dict %}
  File "/srv/ckan/ckanext-hdx_theme/ckanext/hdx_theme/templates/page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/srv/ckan/ckanext-hdx_theme/ckanext/hdx_theme/templates/base.html", line 111, in top-level template code
    {%- block page %}{% endblock -%}
  File "/srv/ckan/ckanext-hdx_theme/ckanext/hdx_theme/templates/page.html", line 10, in block "page"
    {%- block header %}
  File "/srv/ckan/ckanext-hdx_theme/ckanext/hdx_theme/templates/page.html", line 23, in block "header"
    {% include "header.html" %}
  File "/srv/ckan/ckanext-hdx_theme/ckanext/hdx_theme/templates/header.html", line 1, in top-level template code
    {% block header_wrapper %}
  File "/srv/ckan/ckanext-hdx_theme/ckanext/hdx_theme/templates/header.html", line 28, in block "header_wrapper"
    {% set step = data.data.current_step %}
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 372, in getattr
    return getattr(obj, attribute)
UndefinedError: 'str object' has no attribute 'data'
-------------------- >> begin captured logging << --------------------
ckan.helpers: CRITICAL: Helper function `get_user_extra` could not be found
 (are you missing an extension?)
# --------------------- >> end captured logging << ---------------------
## ERROR: ckanext.hdx_org_group.tests.test_controller.test_custom_org_controller.TestMembersController.test_feature_assembly

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/srv/ckan/ckanext-hdx_org_group/ckanext/hdx_org_group/tests/test_controller/test_custom_org_controller.py", line 168, in test_feature_assembly
    'user': user, 'for_view': True,
NameError: global name 'user' is not defined
# 
## FAIL: ckanext.hdx_org_group.tests.test_controller.test_custom_org_controller.TestMembersController.test_capturejs

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/srv/ckan/ckanext-hdx_org_group/ckanext/hdx_org_group/tests/test_controller/test_custom_org_controller.py", line 159, in test_capturejs
    assert cap == True #No error
AssertionError

**Comment by danmihaila** [comment]
fixed
