### ISSUE TITLE
ckan.plugins.core.PluginNotFoundException: requestdata

### ISSUE THREAD

**Issue by kartikbha** [OCHA-DAP/hdx-ckan#4781]
I am getting below error when i am running.
docker exec -t hdxckan_ckan_1 hdxckantool test

Traceback (most recent call last):
  File "/usr/local/bin/nosetests", line 9, in <module>
    load_entry_point('nose==1.3.0', 'console_scripts', 'nosetests')()
  File "/usr/local/lib/python2.7/dist-packages/nose/core.py", line 118, in __init__
    **extra_args)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/local/lib/python2.7/dist-packages/nose/core.py", line 135, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/usr/local/lib/python2.7/dist-packages/nose/config.py", line 345, in configure
    self.plugins.begin()
  File "/usr/local/lib/python2.7/dist-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/usr/local/lib/python2.7/dist-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pylons/test.py", line 74, in begin
    relative_to=path)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py", line 56, in fix_call
    val = callable(*args, **kw)
  File "/srv/ckan/ckan/config/middleware.py", line 59, in make_app
    load_environment(conf, app_conf)
  File "/srv/ckan/ckan/config/environment.py", line 232, in load_environment
    p.load_all(config)
  File "/srv/ckan/ckan/plugins/core.py", line 134, in load_all
    load(*plugins)
  File "/srv/ckan/ckan/plugins/core.py", line 148, in load
    service = _get_service(plugin)
  File "/srv/ckan/ckan/plugins/core.py", line 255, in _get_service
    raise PluginNotFoundException(plugin_name)
ckan.plugins.core.PluginNotFoundException: requestdata

**Comment by teodorescuserban** [comment]
It seems you missed installing all plugins required.
Please make sure you run: `docker exec hdxckan_ckan_1 python setup.py develop`, `docker exec hdxckan_ckan_1 pip install -r requirements.txt` and `docker exec hdxckan_ckan_1 hdxckantool plugins dev`, @kartikbha

**Comment by kartikbha** [comment]
I still have several issues but request data error gone after installing https://github.com/OCHA-DAP/ckanext-requestdata. @teodorescuserban I already installed those plugins/libs.

**Comment by teodorescuserban** [comment]
Please create new issues for your other difficulties (I saw you already added another issue).
Ok to close this one then, @kartikbha ?

**Comment by kartikbha** [comment]
fixed after installing https://github.com/OCHA-DAP/ckanext-requestdata.
